import ballerina/test;

configurable string USER = ?;
configurable string PASSWORD = ?;
configurable string HOST = ?;
configurable string DATABASE = ?;
configurable int PORT = ?;

@test:Config {
    groups: ["basic"]
}
function testCreate() returns error? {
    MedicalItemClient miClient = check new();
    int? id = check miClient->create({
        itemId: 1,
        name: "item name",
        'type: "item type",
        unit: "ml"
    });
    test:assertEquals(id, 1);
}

@test:Config {
    groups: ["basic"]
}
function testCreateWithAutogeneratedKey() returns error? {
    MedicalNeedClient mnClient = check new();
    int? id = check mnClient->create({
        itemId: 1,
        beneficiaryId: 1,
        period: { year: 2022, month: 10, day: 10, hour: 1, minute: 2, second: 3 },
        urgency: "URGENT",
        quantity: 5
    });
    test:assertTrue(id is int);
}

@test:Config {
    groups: ["basic"]
}
function testReadByKey() returns error? {
    MedicalItemClient miClient = check new();
    MedicalItem item = check miClient->readByKey(1);
}